In [4]:
import numpy as np
import math

A = np.array([
    [2, 1, 1, 0],
    [0, -1, 4, 1],
    [2, 2, 0, -2],
    [1, 3, -1, 5]
])
B = np.array([
    [3, -1, 0, 2],
    [7, 1, 0, 2]
])
u = np.array([
    [2],
    [-1],
    [3],
    [1]
])
v = np.array([
    [math.pi],
    [math.e]
])

#验证AB
'''a = np.dot(A, B)
print(a)
输出返回错误 结果不存在
原因 两矩阵的秩不同
'''
#验证BA
'''
与上述同理
'''

#验证vT B
vT = np.transpose(v)
c = np.dot(vT, B)
print(c)
'''验证得存在'''

#验证[u, Au, (A^2)u, (A^3)u]




[[28.45275076 -0.42331083  0.         11.71974896]]


In [4]:
import numpy as np
import math

#初始化u v
u = np.array([
    [1],
    [3],
    [5],
    [7],
    [9],
    [11]
])
v = np.array([
    [-60],
    [-50],
    [-40],
    [-30],
    [-20],
    [-10]
])
uT = np.transpose(u)
vT = np.transpose(v)

#内积
'''inside1 = np.inner(uT, v)
inside2 = np.inner(vT, u)
'''
#外积
outside1 = np.outer(u, vT)
outside2 = np.outer(v, uT)

#output
'''
print('内积uT v为：', inside1)
print('内积vT u为：', inside2)
'''
print('外积u vT为：', outside1)
print('外积v uT为：', outside2)

外积u vT为： [[ -60  -50  -40  -30  -20  -10]
 [-180 -150 -120  -90  -60  -30]
 [-300 -250 -200 -150 -100  -50]
 [-420 -350 -280 -210 -140  -70]
 [-540 -450 -360 -270 -180  -90]
 [-660 -550 -440 -330 -220 -110]]
外积v uT为： [[ -60 -180 -300 -420 -540 -660]
 [ -50 -150 -250 -350 -450 -550]
 [ -40 -120 -200 -280 -360 -440]
 [ -30  -90 -150 -210 -270 -330]
 [ -20  -60 -100 -140 -180 -220]
 [ -10  -30  -50  -70  -90 -110]]


In [2]:
import numpy as np
import math

A = np.random.rand(3, 4)
B = np.random.rand(4, 2)

AT = np.transpose(A)
BT = np.transpose(B)

a = np.dot(A, B)
aT = np.transpose(a)
b = np.dot(BT, AT)

print(a)
print(b)

[[0.86049528 0.27166871]
 [0.86696374 0.30658266]
 [1.102239   0.26884528]]
[[0.86049528 0.86696374 1.102239  ]
 [0.27166871 0.30658266 0.26884528]]
